### ISSUE TITLE
getRangeCellSelection()方法无法获取到值

### ISSUE THREAD

**Issue by tanxuxu** [Happy-Coding-Clans/vue-easytable#590]
在使用this.$refs.VeTable.getRangeCellSelection()的时候，无法获取到选中区域，报错undefined，看了该方法，内部报错：
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.r (<anonymous>:1:83)
    at VueComponent.changeMenu (http://localhost:8083/dist/0.chunk.js:3969:21)
    at invokeWithErrorHandling (http://localhost:8083/dist/vendors.js:5915:30)
    at VueComponent.invoker (http://localhost:8083/dist/vendors.js:3732:20)
    at invokeWithErrorHandling (http://localhost:8083/dist/vendors.js:5915:30)
    at VueComponent.Vue.$emit (http://localhost:8083/dist/vendors.js:5001:17)
    at VueComponent.changeMenu (http://localhost:8083/dist/0.chunk.js:3579:18)
    at click (http://localhost:8083/dist/0.chunk.js:4845:22)
    at invokeWithErrorHandling (http://localhost:8083/dist/vendors.js:5915:30)
    at HTMLSpanElement.invoker (http://localhost:8083/dist/vendors.js:3732:20)

**Comment by huangshuwei** [comment]
麻烦给提供一个可以复现的例子

**Comment by tanxuxu** [comment]
您的邮件我已经查收，我会尽快给您回复

**Comment by tanxuxu** [comment]
[https://codesandbox.io/s/vue-easytable-2-27-1-example-forked-lskyr9?file=/Example.vue](url)
使用场景：
我试图在表格上面加一个工具栏，删除行等按钮，点击按钮能删除掉选中的一行或者多行，但实际上并不能，我担心是因为点击外面，选中自动清空了；
急用，项目等上线，希望作者能给一个解决方案我，真心谢谢！

**Comment by huangshuwei** [comment]
如果工具栏仅仅是删除按钮，你可以通过行多选功能去控制，点击表格外选中也不会消失：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/row-checkbox

**Comment by tanxuxu** [comment]
您的邮件我已经查收，我会尽快给您回复
